Feat/merge pdf
jabardigitalservice/office-service-helper pull request #13
Opened 2023-03-08 08:33 UTC by muhamadabduh

### Overview 
- Merge Generated PDF : document and its attachment
- Merge after generate PDF 
- Output PDF will continue to add footer and Esign 

### Links
- clickup: https://app.clickup.com/t/860putwmd

### Evidence 
- title: Feature(PDF) merge generated pdf document and attachment
- project: SIDEBAR
- participants: @muhamadabduh 
- screenshot:

2023-03-08 09:01 UTC, indraprasetya154 approved these changes
I think we must equate indentation tab on `vscode`, CMIIW, i see a lot of change in yaml file

2023-03-08 09:18 UTC, rachadiannovansyah approved these changes

2023-03-08 09:37 UTC, azophy commented
> I think we must equate indentation tab on `vscode`, CMIIW, i see a lot of change in yaml file

agree. we should add an `.editorconfig` file here to standardize this issue

2023-03-08 09:42 UTC, azophy commented on src/internal/esigns/entity/interface.ts
> +        attachmentUrl: string
actually, it possible to have several attachment (more than one). so we should store this as array of string rather that as a single string. CMIIW

2023-03-08 09:45 UTC, azophy requested changes
I have several comments kang @muhamadabduh

2023-03-09 01:16 UTC, fajarhikmal214 commented on src/internal/pdf-generations/usecase/usecase.ts
> +        return JSON.parse(responseBuffer.toString())
This code needs to make sure that PDF is still good because last time I'm quite struggling😢

2023-03-09 02:29 UTC, fajarhikmal214 commented
Need to adjust after disscusion:
- Attachment Array
- Possibilities Null Attachment
- Returning getObjectAsBuffer directly buffer

2023-03-09 02:50 UTC, muhamadabduh commented on src/internal/esigns/entity/interface.ts
> +        attachmentUrl: string
okay

> > I think we must equate indentation tab on `vscode`, CMIIW, i see a lot of change in yaml file
> 
> agree. we should add an `.editorconfig` file here to standardize this issue

is there any standard that jds use for editorconfig ?

2023-03-09 02:51 UTC, muhamadabduh commented on src/internal/pdf-generations/usecase/usecase.ts
> +            )
I see, thanks for the advice

2023-03-09 03:17 UTC, azophy commented on src/internal/esigns/entity/interface.ts
> +        attachmentUrl: string
I propose this, just made it this morning. credits to @ayocodingit (nuhun mang 🙏 ). https://github.com/jabardigitalservice/dotfiles/blob/main/javascript-typescript/.editorconfig

2023-03-09 05:11 UTC, muhamadabduh commented on src/internal/esigns/entity/interface.ts
> +        attachmentUrl: string
well it seems some configurations in the `.editorconfig` are conflicted with the `.prettierrc` such as : indentation `tabWidth` in the prettier is set to 4 while `indent_size` in the `.editorconfig` is set to 2. 
npm run lint:fix is running prettier anyway, so every time I run the lint script is always reformat according to the `.prettierrc`

2023-03-09 05:45 UTC, azophy commented on src/internal/esigns/entity/interface.ts
> +        attachmentUrl: string
I see. in this case its better for editorconfig to follow prettierrc as prettierrc added earlier to this repo.

2023-03-09 10:39 UTC, azophy requested changes

2023-03-09 14:11 UTC, muhamadabduh commented on src/internal/pdf-generations/usecase/usecase.ts
> +        attachments: string[]
In that case I can't find a way to pass the `attachments` parameter without passing through the `generatePdf()` method. because of what I see in the Esign process is one way process that begin with `generatePdf()` as the first method that will be called. 
any suggestions?

2023-03-09 14:12 UTC, muhamadabduh commented on src/internal/pdf-generations/usecase/usecase.ts
> +            attachmentsBuffer.push(buffer)
I have searched the documentation I found only listObjects, there was nothing like the chatGPT showed getObject(s). So I chose the hard way with many `for .. of` loops which is very painful 😣

2023-03-09 15:30 UTC, muhamadabduh commented on src/internal/pdf-generations/usecase/usecase.ts
> +            }
yes, I feel ambiguous about this line. I overthought about null attachment condition 😅

2023-03-09 15:31 UTC, muhamadabduh commented on src/internal/pdf-generations/usecase/usecase.ts
> +        attachments: string[]
I come up with [this](https://github.com/jabardigitalservice/office-service-helper/pull/13/commits/dd3495ca044d52fca1d9d58ac17736d6d7836ac9), is it good enough ?

2023-03-10 01:15 UTC, azophy commented on src/internal/pdf-generations/usecase/usecase.ts
> +        attachments: string[]
nice kang. thanks 👍

2023-03-10 01:16 UTC, azophy approved these changes
this looks good now. thanks kang @muhamadabduh 👍

2023-03-10 01:20 UTC, fajarhikmal214 commented on src/internal/pdf-generations/usecase/usecase.ts
> +            attachmentsBuffer.push(buffer)
I see, I think it's fine for now

2023-03-10 01:21 UTC, fajarhikmal214 approved these changes
LGTM. But I haven't tested yet

2023-03-10 03:00 UTC, fajarhikmal214 commented on src/internal/pdf-generations/usecase/usecase.ts
> +            return merged
The PDFMerger() instance must define here I guess, because it will merging with previous documents

2023-03-10 03:08 UTC, muhamadabduh commented on src/internal/pdf-generations/usecase/usecase.ts
> +            return merged
yeah, it looks like the instance is called more than once because of the lifecycle of a class. BRB with the fix

2023-03-10 03:21 UTC, merged